import type { Course, Assignment, StudyMaterial, Question, QuestionSet } from './types'

// Generate dates for assignments
const today = new Date()
const getDate = (daysFromNow: number) => {
  const date = new Date(today)
  date.setDate(date.getDate() + daysFromNow)
  return date
}

// 12 Subjects/Courses
export const seedCourses: Course[] = [
  {
    id: 'course-001',
    code: 'CS101',
    name: 'Introduction to Programming',
    description: 'Fundamentals of programming using Python and JavaScript',
    lecturer: 'lecturer-001',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Computer Science',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-002',
    code: 'CS102',
    name: 'Data Structures',
    description: 'Study of arrays, linked lists, stacks, queues, and trees',
    lecturer: 'lecturer-001',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Computer Science',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-003',
    code: 'CS103',
    name: 'Database Management Systems',
    description: 'SQL, relational databases, indexing, and query optimization',
    lecturer: 'lecturer-002',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Computer Science',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-004',
    code: 'CS104',
    name: 'Web Development Fundamentals',
    description: 'HTML, CSS, JavaScript, and responsive web design',
    lecturer: 'lecturer-002',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Computer Science',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-005',
    code: 'MATH201',
    name: 'Calculus I',
    description: 'Limits, derivatives, and applications of calculus',
    lecturer: 'lecturer-003',
    semester: 'first',
    year: 2024,
    credits: 4,
    maxStudents: 60,
    students: ['student-001', 'student-002'],
    department: 'Mathematics',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-006',
    code: 'MATH202',
    name: 'Linear Algebra',
    description: 'Matrices, vectors, eigenvalues, and linear transformations',
    lecturer: 'lecturer-003',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 60,
    students: ['student-001', 'student-002'],
    department: 'Mathematics',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-007',
    code: 'PHYS101',
    name: 'Physics I: Mechanics',
    description: 'Classical mechanics, forces, energy, and motion',
    lecturer: 'lecturer-004',
    semester: 'first',
    year: 2024,
    credits: 4,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Physics',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-008',
    code: 'PHYS102',
    name: 'Physics II: Electricity & Magnetism',
    description: 'Electric fields, currents, magnetic fields, and waves',
    lecturer: 'lecturer-004',
    semester: 'first',
    year: 2024,
    credits: 4,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Physics',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-009',
    code: 'ENG101',
    name: 'English Composition',
    description: 'Writing skills, essay structure, and academic communication',
    lecturer: 'lecturer-005',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 40,
    students: ['student-001', 'student-002'],
    department: 'English',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-010',
    code: 'CHEM101',
    name: 'General Chemistry',
    description: 'Atomic structure, bonding, reactions, and stoichiometry',
    lecturer: 'lecturer-006',
    semester: 'first',
    year: 2024,
    credits: 4,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Chemistry',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-011',
    code: 'BIO101',
    name: 'Biology I: Cell Biology',
    description: 'Cell structure, function, division, and basic genetics',
    lecturer: 'lecturer-007',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 50,
    students: ['student-001', 'student-002'],
    department: 'Biology',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'course-012',
    code: 'HIS101',
    name: 'World History',
    description: 'Major events, civilizations, and developments in world history',
    lecturer: 'lecturer-008',
    semester: 'first',
    year: 2024,
    credits: 3,
    maxStudents: 60,
    students: ['student-001', 'student-002'],
    department: 'History',
    createdAt: new Date('2024-01-15'),
  },
]

// Assignments for each course (3 per course)
export const seedAssignments: Assignment[] = [
  // CS101 Assignments
  {
    id: 'assign-001',
    title: 'Python Basics: Variables and Functions',
    description: 'Create a Python program that demonstrates understanding of variables, data types, and function definitions.',
    type: 'individual',
    courseId: 'course-001',
    dueDate: getDate(7),
    submissionDeadline: getDate(8),
    totalMarks: 20,
    instructions: 'Write a Python script with at least 5 functions demonstrating different concepts.',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-002',
    title: 'JavaScript DOM Manipulation',
    description: 'Build an interactive web page using JavaScript to manipulate the DOM.',
    type: 'individual',
    courseId: 'course-001',
    dueDate: getDate(14),
    submissionDeadline: getDate(15),
    totalMarks: 25,
    instructions: 'Create an interactive form with validation and dynamic content updates.',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-003',
    title: 'Group Project: Todo App',
    description: 'Work in groups to build a functional todo application.',
    type: 'group',
    courseId: 'course-001',
    dueDate: getDate(21),
    submissionDeadline: getDate(22),
    totalMarks: 30,
    instructions: 'Create a complete todo app with add, delete, and mark complete features.',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CS102 Assignments
  {
    id: 'assign-004',
    title: 'Linked List Implementation',
    description: 'Implement a singly linked list with insert, delete, and search operations.',
    type: 'individual',
    courseId: 'course-002',
    dueDate: getDate(6),
    submissionDeadline: getDate(7),
    totalMarks: 25,
    instructions: 'Write clean, well-documented code for a linked list data structure.',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-005',
    title: 'Stack and Queue Operations',
    description: 'Implement stack and queue data structures and solve real-world problems.',
    type: 'individual',
    courseId: 'course-002',
    dueDate: getDate(13),
    submissionDeadline: getDate(14),
    totalMarks: 25,
    instructions: 'Include use cases like browser history (stack) and print queue (queue).',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-006',
    title: 'Tree Traversal Algorithms',
    description: 'Implement binary tree and perform in-order, pre-order, and post-order traversals.',
    type: 'individual',
    courseId: 'course-002',
    dueDate: getDate(20),
    submissionDeadline: getDate(21),
    totalMarks: 30,
    instructions: 'Implement all traversal methods and provide time complexity analysis.',
    attachments: [],
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CS103 Assignments
  {
    id: 'assign-007',
    title: 'SQL Basics: Queries and Joins',
    description: 'Write SQL queries demonstrating SELECT, JOIN, GROUP BY, and aggregate functions.',
    type: 'individual',
    courseId: 'course-003',
    dueDate: getDate(5),
    submissionDeadline: getDate(6),
    totalMarks: 20,
    instructions: 'Complete 10 SQL queries on provided sample database.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-008',
    title: 'Database Design and Normalization',
    description: 'Design a relational database schema and normalize it to 3NF.',
    type: 'group',
    courseId: 'course-003',
    dueDate: getDate(12),
    submissionDeadline: getDate(13),
    totalMarks: 25,
    instructions: 'Create an ER diagram and implement the normalized schema.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-009',
    title: 'Indexing and Query Optimization',
    description: 'Analyze query performance, create appropriate indexes, and optimize slow queries.',
    type: 'individual',
    courseId: 'course-003',
    dueDate: getDate(19),
    submissionDeadline: getDate(20),
    totalMarks: 30,
    instructions: 'Provide before/after performance metrics for optimized queries.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CS104 Assignments
  {
    id: 'assign-010',
    title: 'Responsive Website Design',
    description: 'Build a responsive website using HTML, CSS, and Bootstrap.',
    type: 'individual',
    courseId: 'course-004',
    dueDate: getDate(8),
    submissionDeadline: getDate(9),
    totalMarks: 20,
    instructions: 'Website must be mobile-friendly and follow web design best practices.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-011',
    title: 'Group Project: E-Commerce Landing Page',
    description: 'Create a professional landing page for an e-commerce site.',
    type: 'group',
    courseId: 'course-004',
    dueDate: getDate(15),
    submissionDeadline: getDate(16),
    totalMarks: 30,
    instructions: 'Include product showcase, testimonials, and call-to-action sections.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-012',
    title: 'JavaScript Interactivity',
    description: 'Add interactive features to a website using vanilla JavaScript.',
    type: 'individual',
    courseId: 'course-004',
    dueDate: getDate(22),
    submissionDeadline: getDate(23),
    totalMarks: 25,
    instructions: 'Implement features like image galleries, modals, and form validation.',
    attachments: [],
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // MATH201 Assignments
  {
    id: 'assign-013',
    title: 'Limits and Continuity',
    description: 'Solve problems on limits, continuity, and discontinuities.',
    type: 'individual',
    courseId: 'course-005',
    dueDate: getDate(7),
    submissionDeadline: getDate(8),
    totalMarks: 25,
    instructions: 'Show all work for 15 problems involving limits and continuity.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-014',
    title: 'Derivatives and Applications',
    description: 'Find derivatives using various rules and solve application problems.',
    type: 'individual',
    courseId: 'course-005',
    dueDate: getDate(14),
    submissionDeadline: getDate(15),
    totalMarks: 30,
    instructions: 'Include optimization problems and rate of change applications.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-015',
    title: 'Integration Techniques',
    description: 'Master integration by parts, substitution, and partial fractions.',
    type: 'individual',
    courseId: 'course-005',
    dueDate: getDate(21),
    submissionDeadline: getDate(22),
    totalMarks: 30,
    instructions: 'Solve 20 integration problems using various techniques.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // MATH202 Assignments
  {
    id: 'assign-016',
    title: 'Matrix Operations',
    description: 'Perform matrix addition, multiplication, and find inverses.',
    type: 'individual',
    courseId: 'course-006',
    dueDate: getDate(6),
    submissionDeadline: getDate(7),
    totalMarks: 20,
    instructions: 'Solve 12 problems involving matrix operations and properties.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-017',
    title: 'Determinants and Systems of Equations',
    description: 'Calculate determinants and solve linear systems using matrices.',
    type: 'individual',
    courseId: 'course-006',
    dueDate: getDate(13),
    submissionDeadline: getDate(14),
    totalMarks: 25,
    instructions: 'Use both Gaussian elimination and Cramer\'s rule.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-018',
    title: 'Eigenvalues and Diagonalization',
    description: 'Find eigenvalues, eigenvectors, and diagonalize matrices.',
    type: 'individual',
    courseId: 'course-006',
    dueDate: getDate(20),
    submissionDeadline: getDate(21),
    totalMarks: 30,
    instructions: 'Provide step-by-step solutions with eigenvalue decomposition.',
    attachments: [],
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // PHYS101 Assignments
  {
    id: 'assign-019',
    title: 'Kinematics and Dynamics',
    description: 'Solve problems on motion, forces, and Newton\'s laws.',
    type: 'individual',
    courseId: 'course-007',
    dueDate: getDate(7),
    submissionDeadline: getDate(8),
    totalMarks: 25,
    instructions: 'Include free body diagrams and detailed force analysis.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-020',
    title: 'Work, Energy, and Power',
    description: 'Calculate work, kinetic/potential energy, and solve energy problems.',
    type: 'individual',
    courseId: 'course-007',
    dueDate: getDate(14),
    submissionDeadline: getDate(15),
    totalMarks: 25,
    instructions: 'Apply conservation of energy principles to real scenarios.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-021',
    title: 'Group Project: Physics Experiment Report',
    description: 'Conduct an experiment and write a comprehensive physics report.',
    type: 'group',
    courseId: 'course-007',
    dueDate: getDate(21),
    submissionDeadline: getDate(22),
    totalMarks: 30,
    instructions: 'Include hypothesis, methodology, results, and error analysis.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // PHYS102 Assignments
  {
    id: 'assign-022',
    title: 'Electric Fields and Forces',
    description: 'Calculate electric fields, forces, and potentials.',
    type: 'individual',
    courseId: 'course-008',
    dueDate: getDate(6),
    submissionDeadline: getDate(7),
    totalMarks: 20,
    instructions: 'Use Coulomb\'s law and superposition principle.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-023',
    title: 'Circuits and Current',
    description: 'Analyze DC circuits using Ohm\'s law and Kirchhoff\'s rules.',
    type: 'individual',
    courseId: 'course-008',
    dueDate: getDate(13),
    submissionDeadline: getDate(14),
    totalMarks: 25,
    instructions: 'Draw circuit diagrams and show all calculations.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-024',
    title: 'Magnetic Fields and Waves',
    description: 'Study magnetic fields, electromagnetic induction, and wave properties.',
    type: 'individual',
    courseId: 'course-008',
    dueDate: getDate(20),
    submissionDeadline: getDate(21),
    totalMarks: 30,
    instructions: 'Apply Faraday\'s law and analyze electromagnetic phenomena.',
    attachments: [],
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ENG101 Assignments
  {
    id: 'assign-025',
    title: 'Essay: Personal Narrative',
    description: 'Write a compelling personal narrative essay.',
    type: 'individual',
    courseId: 'course-009',
    dueDate: getDate(10),
    submissionDeadline: getDate(11),
    totalMarks: 20,
    instructions: 'Write 2-3 pages demonstrating strong narrative techniques.',
    attachments: [],
    createdBy: 'lecturer-005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-026',
    title: 'Research Paper: Argumentative Essay',
    description: 'Write an argumentative essay with proper citations.',
    type: 'individual',
    courseId: 'course-009',
    dueDate: getDate(17),
    submissionDeadline: getDate(18),
    totalMarks: 30,
    instructions: 'Use at least 5 credible sources and follow APA format.',
    attachments: [],
    createdBy: 'lecturer-005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-027',
    title: 'Group Project: Presentation and Written Report',
    description: 'Work in groups to research and present on a literary topic.',
    type: 'group',
    courseId: 'course-009',
    dueDate: getDate(24),
    submissionDeadline: getDate(25),
    totalMarks: 30,
    instructions: 'Prepare both a written report and slide presentation.',
    attachments: [],
    createdBy: 'lecturer-005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CHEM101 Assignments
  {
    id: 'assign-028',
    title: 'Atomic Structure and Bonding',
    description: 'Draw Lewis structures, predict molecular geometry, and classify bonds.',
    type: 'individual',
    courseId: 'course-010',
    dueDate: getDate(7),
    submissionDeadline: getDate(8),
    totalMarks: 20,
    instructions: 'Include 15 molecules with detailed structure diagrams.',
    attachments: [],
    createdBy: 'lecturer-006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-029',
    title: 'Stoichiometry and Reactions',
    description: 'Balance chemical equations and solve stoichiometric problems.',
    type: 'individual',
    courseId: 'course-010',
    dueDate: getDate(14),
    submissionDeadline: getDate(15),
    totalMarks: 25,
    instructions: 'Include limiting reactant and percent yield calculations.',
    attachments: [],
    createdBy: 'lecturer-006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-030',
    title: 'Lab Report: Reaction Analysis',
    description: 'Conduct a lab experiment and write a formal report.',
    type: 'individual',
    courseId: 'course-010',
    dueDate: getDate(21),
    submissionDeadline: getDate(22),
    totalMarks: 30,
    instructions: 'Include abstract, methods, results, and discussion sections.',
    attachments: [],
    createdBy: 'lecturer-006',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // BIO101 Assignments
  {
    id: 'assign-031',
    title: 'Cell Structure and Function',
    description: 'Diagram cell organelles and explain their functions.',
    type: 'individual',
    courseId: 'course-011',
    dueDate: getDate(6),
    submissionDeadline: getDate(7),
    totalMarks: 20,
    instructions: 'Create detailed diagrams of plant and animal cells.',
    attachments: [],
    createdBy: 'lecturer-007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-032',
    title: 'Mitosis and Meiosis',
    description: 'Compare and contrast mitosis and meiosis with diagrams.',
    type: 'individual',
    courseId: 'course-011',
    dueDate: getDate(13),
    submissionDeadline: getDate(14),
    totalMarks: 25,
    instructions: 'Show all phases with explanations of key events.',
    attachments: [],
    createdBy: 'lecturer-007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-033',
    title: 'Genetics Problem Set',
    description: 'Solve Mendelian genetics problems including pedigree analysis.',
    type: 'individual',
    courseId: 'course-011',
    dueDate: getDate(20),
    submissionDeadline: getDate(21),
    totalMarks: 30,
    instructions: 'Include Punnett squares and probability calculations.',
    attachments: [],
    createdBy: 'lecturer-007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // HIS101 Assignments
  {
    id: 'assign-034',
    title: 'Ancient Civilizations Analysis',
    description: 'Compare and contrast ancient civilizations and their contributions.',
    type: 'individual',
    courseId: 'course-012',
    dueDate: getDate(9),
    submissionDeadline: getDate(10),
    totalMarks: 20,
    instructions: 'Write 3-4 pages covering at least 3 civilizations.',
    attachments: [],
    createdBy: 'lecturer-008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-035',
    title: 'Historical Event Research',
    description: 'Research and present on a major historical event.',
    type: 'group',
    courseId: 'course-012',
    dueDate: getDate(16),
    submissionDeadline: getDate(17),
    totalMarks: 25,
    instructions: 'Include timeline, key figures, and impact analysis.',
    attachments: [],
    createdBy: 'lecturer-008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'assign-036',
    title: 'World War II Documentary Review',
    description: 'Watch and analyze a documentary about WWII.',
    type: 'individual',
    courseId: 'course-012',
    dueDate: getDate(23),
    submissionDeadline: getDate(24),
    totalMarks: 30,
    instructions: 'Write a critical analysis of the documentary\'s accuracy and perspective.',
    attachments: [],
    createdBy: 'lecturer-008',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Study materials for reference
export const seedMaterials: StudyMaterial[] = [
  {
    id: 'material-001',
    title: 'Python Style Guide (PEP 8)',
    description: 'Official Python coding standards and best practices',
    courseId: 'course-001',
    fileUrl: 'https://www.python.org/dev/peps/pep-0008/',
    fileType: 'link',
    uploadedBy: 'lecturer-001',
    uploadedAt: new Date(),
    tags: ['python', 'programming', 'style'],
  },
  {
    id: 'material-002',
    title: 'JavaScript MDN Documentation',
    description: 'Comprehensive JavaScript reference and tutorials',
    courseId: 'course-001',
    fileUrl: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/',
    fileType: 'link',
    uploadedBy: 'lecturer-001',
    uploadedAt: new Date(),
    tags: ['javascript', 'web', 'documentation'],
  },
  {
    id: 'material-003',
    title: 'Data Structures Visualization',
    description: 'Interactive visualizations of common data structures',
    courseId: 'course-002',
    fileUrl: 'https://www.cs.usfca.edu/~galles/visualization/Algorithms.html',
    fileType: 'link',
    uploadedBy: 'lecturer-001',
    uploadedAt: new Date(),
    tags: ['data-structures', 'visualization', 'learning'],
  },
]

// Sample Questions across different courses
export const seedQuestions: Question[] = [
  // CS101 Questions
  {
    id: 'q-001',
    title: 'Python Variables',
    description: 'Multiple choice about Python variables',
    type: 'multiple-choice',
    courseId: 'course-001',
    text: 'What is the correct way to create a variable in Python?',
    options: ['var x = 5', 'x = 5', 'x := 5', 'set x to 5'],
    correctAnswer: 'x = 5',
    marks: 2,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-002',
    title: 'Function Definition',
    description: 'Short answer about functions',
    type: 'short-answer',
    courseId: 'course-001',
    text: 'Write a Python function that returns the sum of two numbers.',
    marks: 5,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-003',
    title: 'Data Types',
    description: 'Multiple choice about Python data types',
    type: 'multiple-choice',
    courseId: 'course-001',
    text: 'Which of the following is NOT a valid Python data type?',
    options: ['int', 'float', 'string', 'number'],
    correctAnswer: 'number',
    marks: 2,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-004',
    title: 'List Operations',
    description: 'Essay question about list operations',
    type: 'essay',
    courseId: 'course-001',
    text: 'Explain the difference between list append() and extend() methods in Python.',
    marks: 5,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-017',
    title: 'Python Creator',
    description: 'Who created Python?',
    type: 'multiple-choice',
    courseId: 'course-001',
    text: 'Who is the creator of the Python programming language?',
    options: ['Dennis Ritchie', 'Bjarne Stroustrup', 'Guido van Rossum', 'James Gosling'],
    correctAnswer: 'Guido van Rossum',
    marks: 2,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-018',
    title: 'Python Release Year',
    description: 'Python initial public release year',
    type: 'multiple-choice',
    courseId: 'course-001',
    text: 'In which year was the first public release of Python?',
    options: ['1989', '1991', '1995', '2000'],
    correctAnswer: '1991',
    marks: 2,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-019',
    title: 'PEP Meaning',
    description: 'What does PEP stand for',
    type: 'short-answer',
    courseId: 'course-001',
    text: "What does the abbreviation 'PEP' stand for in Python's development process?",
    marks: 3,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CS102 Questions
  {
    id: 'q-005',
    title: 'Linked List Basics',
    description: 'True/False about linked lists',
    type: 'true-false',
    courseId: 'course-002',
    text: 'A linked list allows random access to elements in O(1) time.',
    options: ['True', 'False'],
    correctAnswer: 'False',
    marks: 2,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-006',
    title: 'Stack Operations',
    description: 'Multiple choice about stack',
    type: 'multiple-choice',
    courseId: 'course-002',
    text: 'What is the time complexity of push and pop operations in a stack?',
    options: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'],
    correctAnswer: 'O(1)',
    marks: 3,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-007',
    title: 'Tree Traversal',
    description: 'Short answer about tree traversal',
    type: 'short-answer',
    courseId: 'course-002',
    text: 'Name three methods to traverse a binary tree.',
    marks: 4,
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // CS103 Questions
  {
    id: 'q-008',
    title: 'SQL Joins',
    description: 'Multiple choice about SQL joins',
    type: 'multiple-choice',
    courseId: 'course-003',
    text: 'Which SQL join returns all rows from both tables?',
    options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'],
    correctAnswer: 'FULL OUTER JOIN',
    marks: 3,
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-009',
    title: 'Normalization',
    description: 'Essay on database normalization',
    type: 'essay',
    courseId: 'course-003',
    text: 'Explain the three normal forms (1NF, 2NF, 3NF) in database design.',
    marks: 8,
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // MATH201 Questions
  {
    id: 'q-010',
    title: 'Limit Calculation',
    description: 'Short answer about limits',
    type: 'short-answer',
    courseId: 'course-005',
    text: 'Calculate the limit of (x^2 - 1)/(x - 1) as x approaches 1.',
    marks: 5,
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-011',
    title: 'Derivative Concept',
    description: 'True/False about derivatives',
    type: 'true-false',
    courseId: 'course-005',
    text: 'The derivative of a constant is zero.',
    options: ['True', 'False'],
    correctAnswer: 'True',
    marks: 2,
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // PHYS101 Questions
  {
    id: 'q-012',
    title: 'Newtons Laws',
    description: 'Multiple choice about Newton\'s laws',
    type: 'multiple-choice',
    courseId: 'course-007',
    text: 'Newton\'s second law states that F = ma. What does "a" represent?',
    options: ['Angular momentum', 'Acceleration', 'Area', 'Angle'],
    correctAnswer: 'Acceleration',
    marks: 3,
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-013',
    title: 'Kinetic Energy',
    description: 'Fill in the blank about kinetic energy',
    type: 'fill-blank',
    courseId: 'course-007',
    text: 'The formula for kinetic energy is KE = __________.',
    correctAnswer: '1/2 mv^2 or 0.5 * m * v^2',
    marks: 3,
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ENG101 Questions
  {
    id: 'q-014',
    title: 'Essay Structure',
    description: 'Essay about essay writing',
    type: 'essay',
    courseId: 'course-009',
    text: 'Write a 200-word essay on the importance of effective communication.',
    marks: 10,
    createdBy: 'lecturer-005',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // BIO101 Questions
  {
    id: 'q-015',
    title: 'Cell Organelles',
    description: 'Multiple choice about cell organelles',
    type: 'multiple-choice',
    courseId: 'course-011',
    text: 'Which organelle is responsible for producing energy in a cell?',
    options: ['Nucleus', 'Mitochondria', 'Chloroplast', 'Ribosome'],
    correctAnswer: 'Mitochondria',
    marks: 3,
    createdBy: 'lecturer-007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'q-016',
    title: 'Photosynthesis',
    description: 'Short answer about photosynthesis',
    type: 'short-answer',
    courseId: 'course-011',
    text: 'Write the equation for photosynthesis.',
    marks: 4,
    createdBy: 'lecturer-007',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Sample Question Sets (groups of questions for assignments)
export const seedQuestionSets: QuestionSet[] = [
  {
    id: 'qs-001',
    title: 'Python Basics Quiz',
    description: 'Quiz covering Python fundamentals',
    courseId: 'course-001',
    questions: ['q-001', 'q-002', 'q-003', 'q-004', 'q-017', 'q-018', 'q-019'],
    totalMarks: 20,
    dueDate: getDate(7),
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'qs-002',
    title: 'Data Structures Midterm',
    description: 'Midterm exam on data structures',
    courseId: 'course-002',
    questions: ['q-005', 'q-006', 'q-007'],
    totalMarks: 9,
    dueDate: getDate(14),
    createdBy: 'lecturer-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'qs-003',
    title: 'Database Fundamentals',
    description: 'Quiz on SQL and normalization',
    courseId: 'course-003',
    questions: ['q-008', 'q-009'],
    totalMarks: 11,
    dueDate: getDate(10),
    createdBy: 'lecturer-002',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'qs-004',
    title: 'Calculus Quiz 1',
    description: 'Quiz on limits and derivatives',
    courseId: 'course-005',
    questions: ['q-010', 'q-011'],
    totalMarks: 7,
    dueDate: getDate(8),
    createdBy: 'lecturer-003',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'qs-005',
    title: 'Physics Mechanics Quiz',
    description: 'Quiz on forces and motion',
    courseId: 'course-007',
    questions: ['q-012', 'q-013'],
    totalMarks: 6,
    dueDate: getDate(6),
    createdBy: 'lecturer-004',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
